create table chat_messages (
  id bigint generated by default as identity primary key,
  game_id bigint references games(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);

alter table chat_messages enable row level security;

create policy "Enable read access for all users" on chat_messages for select using (true);
create policy "Enable insert for authenticated users only" on chat_messages for insert with check (auth.role() = 'authenticated');
